import { ITableData } from "./Index";

export const colorCodes = ["#4285F4", "#34A853", "#EFC976", "#EA4335"];


export const LeaderboardData : ITableData[] =[
    {player : "YoungAncient", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
    {player : "Faith Onasanya", moves : 10, time : "01:20"},
]